"""initial analytics schema

Revision ID: 0001_initial_analytics
Revises: 
Create Date: 2026-08-26 15:19:52.643284
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_initial_analytics'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_aggregates',
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('store_id', sa.String(length=16), nullable=False),
    sa.Column('units_sold', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('units_sold >= 0', name='ck_daily_aggregates_units_non_negative'),
    sa.PrimaryKeyConstraint('aggregate_id'),
    sa.UniqueConstraint('sale_date', 'product_id', 'store_id', name='uq_daily_aggregates_grain')
    )
    op.create_index('ix_daily_aggregates_date_category', 'daily_aggregates', ['sale_date', 'category'], unique=False)
    op.create_index(op.f('ix_daily_aggregates_sale_date'), 'daily_aggregates', ['sale_date'], unique=False)
    op.create_table('order_event_facts',
    sa.Column('event_fact_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_fact_id'),
    sa.UniqueConstraint('order_id', 'status', name='uq_order_event_facts_order_status')
    )
    op.create_index(op.f('ix_order_event_facts_occurred_on'), 'order_event_facts', ['occurred_on'], unique=False)
    op.create_index('ix_order_event_facts_status_date', 'order_event_facts', ['status', 'occurred_on'], unique=False)
    op.create_table('outbox_events',
    sa.Column('outbox_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('partition_key', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('outbox_id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_outbox_events_unpublished', 'outbox_events', ['published_at', 'created_at'], unique=False)
    op.create_table('processed_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('consumer_group', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('result_note', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'consumer_group')
    )
    op.create_index(op.f('ix_processed_events_correlation_id'), 'processed_events', ['correlation_id'], unique=False)
    op.create_index('ix_processed_events_event_type', 'processed_events', ['event_type'], unique=False)
    op.create_index('ix_processed_events_processed_at', 'processed_events', ['processed_at'], unique=False)
    op.create_table('sales_facts',
    sa.Column('fact_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('store_id', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_sales_facts_quantity_positive'),
    sa.CheckConstraint('revenue >= 0', name='ck_sales_facts_revenue_non_negative'),
    sa.PrimaryKeyConstraint('fact_id'),
    sa.UniqueConstraint('order_id', 'product_id', name='uq_sales_facts_order_product')
    )
    op.create_index(op.f('ix_sales_facts_customer_id'), 'sales_facts', ['customer_id'], unique=False)
    op.create_index('ix_sales_facts_date_category', 'sales_facts', ['sale_date', 'category'], unique=False)
    op.create_index('ix_sales_facts_date_store', 'sales_facts', ['sale_date', 'store_id'], unique=False)
    op.create_index(op.f('ix_sales_facts_order_id'), 'sales_facts', ['order_id'], unique=False)
    op.create_index('ix_sales_facts_product_date', 'sales_facts', ['product_id', 'sale_date'], unique=False)
    op.create_index(op.f('ix_sales_facts_sale_date'), 'sales_facts', ['sale_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_facts_sale_date'), table_name='sales_facts')
    op.drop_index('ix_sales_facts_product_date', table_name='sales_facts')
    op.drop_index(op.f('ix_sales_facts_order_id'), table_name='sales_facts')
    op.drop_index('ix_sales_facts_date_store', table_name='sales_facts')
    op.drop_index('ix_sales_facts_date_category', table_name='sales_facts')
    op.drop_index(op.f('ix_sales_facts_customer_id'), table_name='sales_facts')
    op.drop_table('sales_facts')
    op.drop_index('ix_processed_events_processed_at', table_name='processed_events')
    op.drop_index('ix_processed_events_event_type', table_name='processed_events')
    op.drop_index(op.f('ix_processed_events_correlation_id'), table_name='processed_events')
    op.drop_table('processed_events')
    op.drop_index('ix_outbox_events_unpublished', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index('ix_order_event_facts_status_date', table_name='order_event_facts')
    op.drop_index(op.f('ix_order_event_facts_occurred_on'), table_name='order_event_facts')
    op.drop_table('order_event_facts')
    op.drop_index(op.f('ix_daily_aggregates_sale_date'), table_name='daily_aggregates')
    op.drop_index('ix_daily_aggregates_date_category', table_name='daily_aggregates')
    op.drop_table('daily_aggregates')
    # ### end Alembic commands ###
