"""initial fulfilment schema

Revision ID: 0001_initial_fulfilment
Revises: 
Create Date: 2026-08-26 13:02:11.523963
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_initial_fulfilment'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fulfilments',
    sa.Column('fulfilment_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('carrier', sa.String(length=24), nullable=True),
    sa.Column('tracking_number', sa.String(length=48), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=False),
    sa.Column('delivery_attempts', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.String(length=120), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'PICKING', 'PACKED', 'SHIPPED', 'DELIVERED', 'FAILED_DELIVERY')", name='ck_fulfilments_status_valid'),
    sa.CheckConstraint("status NOT IN ('SHIPPED', 'DELIVERED', 'FAILED_DELIVERY') OR (tracking_number IS NOT NULL AND carrier IS NOT NULL)", name='ck_fulfilments_shipped_has_tracking'),
    sa.CheckConstraint('delivery_attempts >= 0', name='ck_fulfilments_attempts_non_negative'),
    sa.PrimaryKeyConstraint('fulfilment_id'),
    sa.UniqueConstraint('tracking_number')
    )
    op.create_index(op.f('ix_fulfilments_customer_id'), 'fulfilments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_fulfilments_order_id'), 'fulfilments', ['order_id'], unique=True)
    op.create_index('ix_fulfilments_status_created', 'fulfilments', ['status', 'created_at'], unique=False)
    op.create_table('outbox_events',
    sa.Column('outbox_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('partition_key', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('outbox_id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_outbox_events_unpublished', 'outbox_events', ['published_at', 'created_at'], unique=False)
    op.create_table('processed_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('consumer_group', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('result_note', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'consumer_group')
    )
    op.create_index(op.f('ix_processed_events_correlation_id'), 'processed_events', ['correlation_id'], unique=False)
    op.create_index('ix_processed_events_event_type', 'processed_events', ['event_type'], unique=False)
    op.create_index('ix_processed_events_processed_at', 'processed_events', ['processed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_processed_events_processed_at', table_name='processed_events')
    op.drop_index('ix_processed_events_event_type', table_name='processed_events')
    op.drop_index(op.f('ix_processed_events_correlation_id'), table_name='processed_events')
    op.drop_table('processed_events')
    op.drop_index('ix_outbox_events_unpublished', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index('ix_fulfilments_status_created', table_name='fulfilments')
    op.drop_index(op.f('ix_fulfilments_order_id'), table_name='fulfilments')
    op.drop_index(op.f('ix_fulfilments_customer_id'), table_name='fulfilments')
    op.drop_table('fulfilments')
    # ### end Alembic commands ###
