"""initial inventory schema

Revision ID: 0001_initial_inventory
Revises: 
Create Date: 2026-08-26 00:02:03.993827
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_initial_inventory'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_locations_code'), 'locations', ['code'], unique=True)
    op.create_table('stock_movements',
    sa.Column('movement_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('movement_type', sa.String(length=16), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('available_after', sa.Integer(), nullable=False),
    sa.Column('reserved_after', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("movement_type IN ('RESERVE', 'RELEASE', 'COMMIT', 'RESTOCK', 'ADJUSTMENT')", name='ck_stock_movements_type_valid'),
    sa.PrimaryKeyConstraint('movement_id')
    )
    op.create_index('ix_stock_movements_product_created', 'stock_movements', ['product_id', 'created_at'], unique=False)
    op.create_index('ix_stock_movements_reference_id', 'stock_movements', ['reference_id'], unique=False)
    op.create_table('inventory',
    sa.Column('inventory_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('reorder_threshold', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available_quantity >= 0', name='ck_inventory_available_non_negative'),
    sa.CheckConstraint('reorder_threshold >= 0', name='ck_inventory_threshold_non_negative'),
    sa.CheckConstraint('reserved_quantity >= 0', name='ck_inventory_reserved_non_negative'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('inventory_id'),
    sa.UniqueConstraint('product_id', 'location_id', name='uq_inventory_product_location')
    )
    op.create_index('ix_inventory_location_id', 'inventory', ['location_id'], unique=False)
    op.create_index('ix_inventory_product_id', 'inventory', ['product_id'], unique=False)
    op.create_table('reservations',
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('HELD', 'RELEASED', 'COMMITTED')", name='ck_reservations_status_valid'),
    sa.CheckConstraint('quantity > 0', name='ck_reservations_quantity_positive'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('reservation_id'),
    sa.UniqueConstraint('order_id', 'product_id', 'location_id', name='uq_reservation_order_product_location')
    )
    op.create_index('ix_reservations_order_id', 'reservations', ['order_id'], unique=False)
    op.create_index('ix_reservations_status', 'reservations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reservations_status', table_name='reservations')
    op.drop_index('ix_reservations_order_id', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index('ix_inventory_product_id', table_name='inventory')
    op.drop_index('ix_inventory_location_id', table_name='inventory')
    op.drop_table('inventory')
    op.drop_index('ix_stock_movements_reference_id', table_name='stock_movements')
    op.drop_index('ix_stock_movements_product_created', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_locations_code'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
