"""add event outbox and processed events

Revision ID: 0002_event_tables
Revises: 0001_initial_order
Create Date: 2026-08-26 07:49:27.733500
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002_event_tables'
down_revision: Union[str, None] = '0001_initial_order'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('outbox_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('partition_key', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('outbox_id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_outbox_events_unpublished', 'outbox_events', ['published_at', 'created_at'], unique=False)
    op.create_table('processed_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('consumer_group', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('result_note', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'consumer_group')
    )
    op.create_index(op.f('ix_processed_events_correlation_id'), 'processed_events', ['correlation_id'], unique=False)
    op.create_index('ix_processed_events_event_type', 'processed_events', ['event_type'], unique=False)
    op.create_index('ix_processed_events_processed_at', 'processed_events', ['processed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_processed_events_processed_at', table_name='processed_events')
    op.drop_index('ix_processed_events_event_type', table_name='processed_events')
    op.drop_index(op.f('ix_processed_events_correlation_id'), table_name='processed_events')
    op.drop_table('processed_events')
    op.drop_index('ix_outbox_events_unpublished', table_name='outbox_events')
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
